[2024-11-30T06:22:40.325+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-30T06:22:40.386+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: complete-dag.fetch_forecast_weather manual__2024-11-30T06:22:33.196088+00:00 [queued]>
[2024-11-30T06:22:40.393+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: complete-dag.fetch_forecast_weather manual__2024-11-30T06:22:33.196088+00:00 [queued]>
[2024-11-30T06:22:40.394+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-30T06:22:40.408+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_forecast_weather> on 2024-11-30 06:22:33.196088+00:00
[2024-11-30T06:22:40.424+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=8878) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-30T06:22:40.426+0000] {standard_task_runner.py:63} INFO - Started process 8891 to run task
[2024-11-30T06:22:40.425+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'complete-dag', 'fetch_forecast_weather', 'manual__2024-11-30T06:22:33.196088+00:00', '--job-id', '340', '--raw', '--subdir', 'DAGS_FOLDER/complete_dag.py', '--cfg-path', '/tmp/tmpet8osxjy']
[2024-11-30T06:22:40.427+0000] {standard_task_runner.py:91} INFO - Job 340: Subtask fetch_forecast_weather
[2024-11-30T06:22:40.552+0000] {task_command.py:426} INFO - Running <TaskInstance: complete-dag.fetch_forecast_weather manual__2024-11-30T06:22:33.196088+00:00 [running]> on host b09a94790db6
[2024-11-30T06:22:40.752+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='complete-dag' AIRFLOW_CTX_TASK_ID='fetch_forecast_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-11-30T06:22:33.196088+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-30T06:22:33.196088+00:00'
[2024-11-30T06:22:40.757+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-30T06:22:41.660+0000] {python.py:237} INFO - Done. Returned value was:          Date  temperature_2m_max  ...  windspeed_10m_max  avg_temperature
0  2024-11-29                16.0  ...               13.5             9.60
1  2024-11-30                15.6  ...               11.3            10.80
2  2024-12-01                15.1  ...               24.1             9.45
3  2024-12-02                 6.7  ...               20.3             2.85
4  2024-12-03                 8.3  ...                3.7             2.90
5  2024-12-04                 8.8  ...               13.0             4.40
6  2024-12-05                10.2  ...               14.3             4.30

[7 rows x 7 columns]
[2024-11-30T06:22:41.764+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-30T06:22:42.087+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=complete-dag, task_id=fetch_forecast_weather, run_id=manual__2024-11-30T06:22:33.196088+00:00, execution_date=20241130T062233, start_date=20241130T062240, end_date=20241130T062242
[2024-11-30T06:22:42.494+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-30T06:22:42.510+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
