[2024-11-30T08:05:09.446+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-30T08:05:09.488+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt-viz-dag.dbt_snapshot manual__2024-11-30T08:04:37.736321+00:00 [queued]>
[2024-11-30T08:05:09.499+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt-viz-dag.dbt_snapshot manual__2024-11-30T08:04:37.736321+00:00 [queued]>
[2024-11-30T08:05:09.500+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-30T08:05:09.519+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_snapshot> on 2024-11-30 08:04:37.736321+00:00
[2024-11-30T08:05:09.529+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt-viz-dag', 'dbt_snapshot', 'manual__2024-11-30T08:04:37.736321+00:00', '--job-id', '400', '--raw', '--subdir', 'DAGS_FOLDER/dbt-viz-dag.py', '--cfg-path', '/tmp/tmplblxsica']
[2024-11-30T08:05:09.532+0000] {standard_task_runner.py:91} INFO - Job 400: Subtask dbt_snapshot
[2024-11-30T08:05:09.533+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=16007) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-30T08:05:09.534+0000] {standard_task_runner.py:63} INFO - Started process 16008 to run task
[2024-11-30T08:05:09.584+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt-viz-dag.dbt_snapshot manual__2024-11-30T08:04:37.736321+00:00 [running]> on host b09a94790db6
[2024-11-30T08:05:09.741+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt-viz-dag' AIRFLOW_CTX_TASK_ID='dbt_snapshot' AIRFLOW_CTX_EXECUTION_DATE='2024-11-30T08:04:37.736321+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-30T08:04:37.736321+00:00'
[2024-11-30T08:05:09.743+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-30T08:05:09.759+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-30T08:05:09.762+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt snapshot --profiles-dir /opt/***/dbt_viz --project-dir /opt/***/dbt_viz']
[2024-11-30T08:05:09.775+0000] {subprocess.py:86} INFO - Output:
[2024-11-30T08:05:12.500+0000] {subprocess.py:93} INFO - [0m08:05:12  Running with dbt=1.8.7
[2024-11-30T08:05:13.839+0000] {subprocess.py:93} INFO - [0m08:05:13  Registered adapter: snowflake=1.8.4
[2024-11-30T08:05:14.651+0000] {subprocess.py:93} INFO - [0m08:05:14  Found 5 models, 1 test, 4 sources, 459 macros
[2024-11-30T08:05:14.655+0000] {subprocess.py:93} INFO - [0m08:05:14
[2024-11-30T08:05:14.656+0000] {subprocess.py:93} INFO - [0m08:05:14  Nothing to do. Try checking your model configs and model specification args
[2024-11-30T08:05:15.485+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-30T08:05:15.488+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-30T08:05:15.521+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt-viz-dag, task_id=dbt_snapshot, run_id=manual__2024-11-30T08:04:37.736321+00:00, execution_date=20241130T080437, start_date=20241130T080509, end_date=20241130T080515
[2024-11-30T08:05:15.585+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-30T08:05:15.604+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-30T08:05:15.608+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
