[2024-11-12T02:52:03.630+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T02:52:03.996+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T02:51:57.306478+00:00 [queued]>
[2024-11-12T02:52:04.026+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T02:51:57.306478+00:00 [queued]>
[2024-11-12T02:52:04.027+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T02:52:04.070+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-12 02:51:57.306478+00:00
[2024-11-12T02:52:04.097+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run', 'manual__2024-11-12T02:51:57.306478+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpq_1o9837']
[2024-11-12T02:52:04.129+0000] {standard_task_runner.py:91} INFO - Job 128: Subtask dbt_run
[2024-11-12T02:52:04.134+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=419) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T02:52:04.135+0000] {standard_task_runner.py:63} INFO - Started process 426 to run task
[2024-11-12T02:52:05.178+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T02:51:57.306478+00:00 [running]> on host e9e87141c083
[2024-11-12T02:52:06.294+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T02:51:57.306478+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T02:51:57.306478+00:00'
[2024-11-12T02:52:06.304+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T02:52:06.486+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T02:52:06.495+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-12T02:52:06.523+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T02:52:14.940+0000] {subprocess.py:93} INFO - [0m02:52:14  Running with dbt=1.8.7
[2024-11-12T02:52:20.204+0000] {subprocess.py:93} INFO - [0m02:52:20  Registered adapter: snowflake=1.8.4
[2024-11-12T02:52:21.666+0000] {subprocess.py:93} INFO - [0m02:52:21  Encountered an error:
[2024-11-12T02:52:21.667+0000] {subprocess.py:93} INFO - 'dbt_snowflake://macros/apply_grants.sql'
[2024-11-12T02:52:21.668+0000] {subprocess.py:93} INFO - [0m02:52:21  Traceback (most recent call last):
[2024-11-12T02:52:21.669+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 138, in wrapper
[2024-11-12T02:52:21.669+0000] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2024-11-12T02:52:21.670+0000] {subprocess.py:93} INFO -                       ^^^^^^^^^^^^^^^^^^^^^
[2024-11-12T02:52:21.670+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 101, in wrapper
[2024-11-12T02:52:21.671+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-11-12T02:52:21.671+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2024-11-12T02:52:21.671+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 218, in wrapper
[2024-11-12T02:52:21.672+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-11-12T02:52:21.672+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2024-11-12T02:52:21.673+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 247, in wrapper
[2024-11-12T02:52:21.673+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-11-12T02:52:21.673+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2024-11-12T02:52:21.674+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 294, in wrapper
[2024-11-12T02:52:21.674+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-11-12T02:52:21.675+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2024-11-12T02:52:21.675+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 320, in wrapper
[2024-11-12T02:52:21.675+0000] {subprocess.py:93} INFO -     ctx.obj["manifest"] = parse_manifest(
[2024-11-12T02:52:21.676+0000] {subprocess.py:93} INFO -                           ^^^^^^^^^^^^^^^
[2024-11-12T02:52:21.677+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 1898, in parse_manifest
[2024-11-12T02:52:21.677+0000] {subprocess.py:93} INFO -     manifest = ManifestLoader.get_full_manifest(
[2024-11-12T02:52:21.677+0000] {subprocess.py:93} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-12T02:52:21.678+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 330, in get_full_manifest
[2024-11-12T02:52:21.678+0000] {subprocess.py:93} INFO -     manifest = loader.load()
[2024-11-12T02:52:21.678+0000] {subprocess.py:93} INFO -                ^^^^^^^^^^^^^
[2024-11-12T02:52:21.679+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 399, in load
[2024-11-12T02:52:21.679+0000] {subprocess.py:93} INFO -     self.load_and_parse_macros(project_parser_files)
[2024-11-12T02:52:21.679+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 676, in load_and_parse_macros
[2024-11-12T02:52:21.680+0000] {subprocess.py:93} INFO -     block = FileBlock(self.manifest.files[file_id])
[2024-11-12T02:52:21.680+0000] {subprocess.py:93} INFO -                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
[2024-11-12T02:52:21.680+0000] {subprocess.py:93} INFO - KeyError: 'dbt_snowflake://macros/apply_grants.sql'
[2024-11-12T02:52:21.681+0000] {subprocess.py:93} INFO - 
[2024-11-12T02:52:22.612+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-12T02:52:22.617+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T02:52:22.635+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-12T02:52:22.656+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run, run_id=manual__2024-11-12T02:51:57.306478+00:00, execution_date=20241112T025157, start_date=20241112T025203, end_date=20241112T025222
[2024-11-12T02:52:22.682+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 128 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 426)
[2024-11-12T02:52:22.733+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T02:52:22.762+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T02:52:22.769+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
